### ISSUE TITLE
Table advice needs some work.

### ISSUE THREAD

**Issue by mezapata** [cehfisher/a11y-style-guide#124]
The summary attribute of the table element is obsolete in HTML5. (Screen reader support for this attribute has been spotty.) 
Similarly, the thead, tfoot, and tbody elements provide no accessibility functionality.
Reference: http://webaim.org/techniques/tables/data

**Comment by cehfisher** [comment]
@mezapata thanks for the info! I was going primarily off of the W3C table tutorials to include some extra a11y pieces to tables (I agree most tables are pretty decent out of the box). They mention the use of summaries here - https://www.w3.org/WAI/tutorials/tables/caption-summary/
It could be that I need to make it clearer that summaries and captions aren't necessary, but optional?

For the thead, tfoot, and tbody elements, those are added to make the tables responsive. I believe that a lot of tables are deemed "inaccessible" due to issues with responsiveness. This obviously wouldn't be an issue for a user using a screenreader, but I'm working on making the components accessible to *all* users. By making a table responsive, we cover users who have issues of mobility, who might find it more difficult to scroll left to right to read a table. At least that is the thinking behind making the tables responsive...probably good info to include as well.

**Comment by cehfisher** [comment]
thanks @mezapata. made some updates, let me know if anything else needs to be updated. thanks again for taking the time to make a ticket.
