### ISSUE TITLE
read more should use aria-describedby instead of aria-labelledby

### ISSUE THREAD

**Issue by 7mary4** [cehfisher/a11y-style-guide#134]
Hi, thank you for putting this together.
On the [read-more links](https://github.com/cehfisher/a11y-style-guide/blob/master/src/components/read-more/read-more.twig), you suggest using aria-labelledby to provide unique link text for a read more element. This is not wrong, however the aria-labelledby attribute will replace the text node with the content from the heading. So, instead of hearing "link read more", you would hear "link storms hit east coast". That's not terrible.

Another option is to use aria-describedby. This will not replace the text node, but will add the heading text as additional information.  So you would hear "link read more {short pause} Storms hit east coast".

**Comment by cehfisher** [comment]
hi @7mary4! thanks for the feedback on the A11Y style guide. I am trying to capture real-world scenarios as I come across them and list all the options available to developers (because sometimes we can only change certain elements). there are certainly options that are more accessible than others. this is a perfect example of that. i will plan to add your example to the guide in the next PR, but it got me thinking...maybe adding a star/rating system to the examples would be helpful? So people know that if you _can_ change everything (markup, content, styles, whatnot), use option A, if your hands are tied on something (ie. markup) use option B, etc.

**Comment by scottaohara** [comment]
The problem I've found with using ```aria-describedby``` for read more links is that context doesn't bubble up to things like VO's web router, where ```aria-label``` and ```aria-labelledby``` does.  

Additionally, from the testing I've done with screen reader users, they don't appreciate the delay in that described by adds, since it slows down their navigating by links, when using Voice Over.

With all that said, both should definitely be proposed as options, but there are pros and cons to each.

**Comment by cehfisher** [comment]
thanks @scottaohara for that perspective as well. let's brainstorm on ways to rate levels of accessibility. the main issue being that one method might be best for one type of disability but hinder another...or be good for one AT but not another. this is one of the reasons i started this thing in the first place...there are a lot of paths to go down, but hard to know which one is the best. and that seems to be a bit of a moving target at times.

**Comment by cehfisher** [comment]
OK just updated the Read More section (http://a11y-style-guide.com/style-guide/section-general.html#kssref-general-read-more). take a look and see if I missed anything @scottaohara @7mary4

**Comment by scottaohara** [comment]
The ```aria-describedby``` example would read as follows to someone navigating by links alone:

Read More 'pause' This is a movie quote from The Treasure of the Sierra Madre.

It's set up properly, but probably doesn't provide the best context as to what the link is in relation to.  I'd recommend putting the info ID on the heading associated with the example.

**Comment by cehfisher** [comment]
ahh true...updating the example to make more sense. reopen if you need more changes, but hopefully this last update covers it for now :)
