### ISSUE TITLE
Should teach input type=image for graphical buttons

### ISSUE THREAD

**Issue by dengeist** [cehfisher/a11y-style-guide#140]
Right now, the only advice for graphical buttons is:

> If the `button` only contains an `<img>` element, make sure to set its alt attribute. If it only contains an icon use aria-label.

... which is correct _if_ you decide to make a graphical button this way, but buttons should only contain phrasing content ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)). A quick mention & demo of [`<input type="image">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/image) might be better advice.

**Comment by scottaohara** [comment]
Phrasing content [includes images](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content), and is perfectly acceptable as the child of a button element, as long as there is appropriate alt text.

I would suggest we don't replace the current example, but add your suggestion as another option, since both are valid.

**Comment by cehfisher** [comment]
@scottaohara Elias did include a new example in his PR. I added notes to the PR itself on a couple of changes i would like to see. if you do not have time @dengeist to make these changes, let me know and i will update the PR when i have time this week. thanks again for submitting code!!
