### ISSUE TITLE
Build tabs component

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#69]
Creating a ticket to track progress on tabs component.

**Comment by MichielBijl** [comment]
Do you have a particular design for this in mind?

**Comment by cehfisher** [comment]
No particular designs in mind...just something that matches the overall look/feel of the site.

**Comment by kendrick** [comment]
I've added accessible tabs to my own pattern library and would love to contribute them to this one. I'll update the look & feel and send a PR.

**Comment by cehfisher** [comment]
awesome! do you have a link to your pattern library too? just wondering how I could contribute back to you as well.

**Comment by kendrick** [comment]
Sure, it's at https://github.com/pier1/rocketbelt. Our pattern [swaps between accordions & tabs](https://github.com/Pier1/rocketbelt/tree/develop/rocketbelt/components/tabcordions) depending on the viewport width, but I don't know that I'd make the same decision again. 😀 I'll plan on implementing just the tabs for this PR.

**Comment by cehfisher** [comment]
@kendrick how's the progress going so far?

**Comment by kendrick** [comment]
It's… going. 😄 Haven't been able to get back to it in a few days, but should be able to continue working on this & the typography issue later in the week.

**Comment by kendrick** [comment]
(Almost done!)

**Comment by kendrick** [comment]
@cehfisher I have this wrapped up and should be able to do some final cleanup & PR tomorrow evening. Just curious where you'd like this to live? I have it in the "Structure" section at the moment but am happy to put it wherever you'd like. Thanks!

**Comment by cehfisher** [comment]
@kendrick sorry it took me a bit of time to get back to this PR. I updated the styling a bit, added the new tab JS to the index page, and ran the demo update script. you can see it live here - http://a11y-style-guide.com/style-guide/section-structure.html#kssref-structure-tabs

i'd like to have @scottaohara do a quick JS/screenreader check to see if I missed anything in my testing.

thanks again @kendrick for your work on this!

**Comment by scottaohara** [comment]
Hey there @kendrick, 

First off, thank you for the submission.  I do have a few questions/comments about what you've submitted.

1. I am unsure of why you are using `aria-selected` and `aria-expanded`?  The `aria-expanded` is not presently being updated when navigating the tab buttons. VoiceOver presently ignores the `aria-expanded`, but JAWS + NVDA will announce a tab as being collapsed and selected, which is clearly not correct due to the auto opening nature of this tab component.  I'd suggest removing the `aria-expanded` all together as the way this component works, there shouldn't be an instance where a user can be focused on an unopened tab.

2. The specification for `aria-posinset` says it's not required to be used if all elements of a set are present in the DOM.  It's a neat add, though.  I only wonder if it'd be a good idea to mention this should be optional for this particular demonstration, and note when it's actually required. The current note makes it seem like it is a general requirement. This would likely affect `aria-setsize` usage as well.

3. When interacting with this component with VoiceOver with Safari 11.0.1 & high sierra, the help text reads "to select this option, press control option space".  The tabpanel is already open, and activating the tab itself doesn't do anything.  This may be a good opportunity to actually move focus from the tab to the tabpanel though, and would help mitigate the fact that JAWS + NVDA will go into forms mode, when selecting these tabs, and a user presently has to exit forms mode to exit the tabs.  (the overriding of the up/down arrows is partially the culprit here, and those keys should not be overridden by JavaScript, as they are pretty essential for AT navigation. The recommendation to use up/down arrow keys in a tab widget have been removed from the current aria 1.1 draft for tab widgets due to this reason). 

Even if removing the JS overwrite of up/down arrows, it still probably makes sense to programmatically set focus on the tabpanel on the activation of a tab, as I presently can't think of a way to make VoiceOver not announce those activation keys...

4. Generally, I'd be interested in your thoughts on why you went with the auto-selection interaction pattern rather than the interaction pattern that dictates a user manually select a tab to open it.  This is not meant as a criticism, I am just generally curious as I find both to be acceptable interaction patterns depending on the situation / tested user expectations.

Thanks again!

**Comment by cehfisher** [comment]
thanks @scottaohara for reviewing. based on the info you provided, I added a "draft" tag to the pattern (but still left it live for now).

**Comment by kendrick** [comment]
Hey @scottaohara, thanks for your review & thoughtful comments.

> I am unsure of why you are using `aria-selected` and `aria-expanded`?

Great catch; I adapted this component from a component that switches between tabs & an accordion depending on the viewport width. `aria-expanded` is there for the accordion mode and I overlooked removing it.

> The specification for aria-posinset says it's not required to be used if all elements of a set are present in the DOM. It's a neat add, though. I only wonder if it'd be a good idea to mention this should be optional for this particular demonstration, and note when it's actually required. The current note makes it seem like it is a general requirement. This would likely affect aria-setsize usage as well.

TIL! It'll be nice to clean up the attributes of a bunch of my own code that has a static number of always-present tabs.

> When interacting with this component with VoiceOver with Safari 11.0.1 & high sierra, the help text reads "to select this option, press control option space". The tabpanel is already open, and activating the tab itself doesn't do anything. This may be a good opportunity to actually move focus from the tab to the tabpanel though […] (the overriding of the up/down arrows is partially the culprit here, and those keys should not be overridden by JavaScript, as they are pretty essential for AT navigation. The recommendation to use up/down arrow keys in a tab widget have been removed from the current aria 1.1 draft for tab widgets due to this reason).

Yup, sounds like the arrow overrides should definitely get the axe.

> Generally, I'd be interested in your thoughts on why you went with the auto-selection interaction pattern rather than the interaction pattern that dictates a user manually select a tab to open it. 

Primarily because I wanted to minimize keypresses when navigating out of a tabpanel and back through the tabs—though this would be mitigated if tabpanels were autofocused when the tab was selected.

Thanks again for your comments—though I'm highly enthusiastic about accessibility I'm still a relative n00b. (@cehfisher I'm happy to make some updates based on the above and should be able to PR later in the week.)

**Comment by scottaohara** [comment]
@kendrick "relative noob" is relative :)  Outside of the up/down arrow overwrite and the unnecessary aria-expanded, this was a pretty solid submission.  Looking forward to the updated PR.  Thanks again.

**Comment by cehfisher** [comment]
any progress on this issue @kendrick or @scottaohara?

**Comment by kendrick** [comment]
Hey hey, just got back from some post-holiday travel but I should be able
to get it cleaned up this weekend or early next week!
