### ISSUE TITLE
Jump to top button

### ISSUE THREAD

**Issue by cehfisher** [cehfisher/a11y-style-guide#86]
The style guide can get vertically long, need a jump to top button

**Comment by scottaohara** [comment]
i could take this, but i have a few questions:

1. should this be a visible back to top link, or visible on keyboard focus only?  
2. should it point to the navigation or the main content area?  visually on activation it'll have the same effect, since the nav is fixed (unless this ends up changing for small screen, as then there will be a difference.
3. is there reason for maybe both?  1 visible back to top of content area / 2 keyboard focus/visible for back to navigation?

4. you're over thinking this, scott?

**Comment by cehfisher** [comment]
@scottaohara 
1. i was thinking it would be a visible back to top link, that could also be used by people using keyboards only
2. back to main content area is typically what i have seen
3. yes, that might be good...not sure if overkill
4. yes...but i do that too :)

**Comment by cehfisher** [comment]
do you want me to create the icon for this? to make sure it works with the existing theme?

**Comment by scottaohara** [comment]
sure!  just let me know when you got that into the repo and i'll make sure to use it in my commit

**Comment by cehfisher** [comment]
feel free to start the feature and i can work on the icon. it won't be until later today

**Comment by scottaohara** [comment]
ok

**Comment by cehfisher** [comment]
Updated on demo site. I added an icon to indicate direction up to the top, plus made a minor edit to the JS. Thanks for the work on this @scottaohara!
